apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: airbnb-agent
  name: airbnb-agent
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: airbnb-agent
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-06-24T19:55:03+09:00"
      labels:
        app: airbnb-agent
    spec:
      containers:
        - env:
            - name: GOOGLE_API_KEY
              value: AIzaSyDUKk9SF6bD7lLHfFxj3CJ0DPGJeyPadD4
            - name: HOST
              value: airbnb-agent
            - name: PORT
              value: "10002"
          image: ghcr.io/uengine-oss/airbnb-agent:latest
          imagePullPolicy: Always
          name: airbnb-agent
          ports:
            - containerPort: 10002
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              ephemeral-storage: 1Gi
              memory: 512Mi
            requests:
              cpu: 200m
              ephemeral-storage: 1Gi
              memory: 256Mi
          securityContext:
            capabilities:
              drop:
                - NET_RAW
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/arch
          operator: Equal
          value: amd64