apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  name: frontend-deployment
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - env:
            - name: VITE_OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  key: OPENAI_API_KEY
                  name: openai-secret
            - name: VITE_SUPABASE_URL
              valueFrom:
                configMapKeyRef:
                  key: SUPABASE_URL
                  name: my-config
            - name: VITE_SUPABASE_KEY
              valueFrom:
                secretKeyRef:
                  key: SUPABASE_KEY
                  name: my-secrets
          image: ghcr.io/uengine-oss/process-gpt:bfe4810
          imagePullPolicy: IfNotPresent
          name: frontend
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              ephemeral-storage: 1Gi
            requests:
              cpu: 100m
              ephemeral-storage: 1Gi
              memory: 128Mi
          securityContext:
            capabilities:
              drop:
                - NET_RAW
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/arch
          operator: Equal
          value: amd64
