apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: gateway
  name: gateway
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gateway
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"     
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: JWT_SECRET
                  name: my-secrets
          image: ghcr.io/uengine-oss/process-gpt-gateway:v1.0.7
          imagePullPolicy: IfNotPresent
          name: gateway
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              ephemeral-storage: 1Gi
            requests:
              cpu: 500m
              ephemeral-storage: 1Gi
              memory: 2Gi
          securityContext:
            capabilities:
              drop:
                - NET_RAW
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/arch
          operator: Equal
          value: amd64
