apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  name: memento-deployment
  namespace: dev
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: memento
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: memento
    spec:
      containers:
        - env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  key: OPENAI_API_KEY
                  name: openai-secret
            - name: SUPABASE_URL
              valueFrom:
                configMapKeyRef:
                  key: SUPABASE_URL
                  name: my-config
            - name: SUPABASE_KEY
              valueFrom:
                secretKeyRef:
                  key: SERVICE_ROLE_KEY
                  name: my-secrets
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secrets/credentials.json
          image: ghcr.io/uengine-oss/process-gpt-memento:2e47a8f
          imagePullPolicy: IfNotPresent
          name: memento
          ports:
            - containerPort: 8005
              protocol: TCP
          resources:
            limits:
              ephemeral-storage: 1Gi
            requests:
              cpu: 100m
              ephemeral-storage: 1Gi
              memory: 128Mi
          securityContext:
            capabilities:
              drop:
                - NET_RAW
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /secrets
              name: google-credentials
              readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/arch
          operator: Equal
          value: amd64
      volumes:
        - name: google-credentials
          secret:
            defaultMode: 420
            secretName: google-credentials
