apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: scaling-agent
  name: scaling-agent
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: scaling-agent
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: scaling-agent
    spec:
      containers:
        - env:
            - name: SUPABASE_URL
              valueFrom:
                configMapKeyRef:
                  key: SUPABASE_URL
                  name: my-config
            - name: SUPABASE_KEY
              valueFrom:
                secretKeyRef:
                  key: SUPABASE_KEY
                  name: my-secrets
            - name: NAMESPACE
              value: default
            - name: POLLING_INTERVAL
              value: 15s
          image: asia-northeast3-docker.pkg.dev/process-gpt-419207/process-gpt-prod/scaling-agent:v0.1.6
          imagePullPolicy: IfNotPresent
          name: scaling-agent
          resources:
            limits:
              ephemeral-storage: 1Gi
            requests:
              cpu: 500m
              ephemeral-storage: 1Gi
              memory: 2Gi
          securityContext:
            capabilities:
              drop:
                - NET_RAW
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      serviceAccount: scaling-agent-sa
      serviceAccountName: scaling-agent-sa
      terminationGracePeriodSeconds: 30
