apiVersion: apps/v1
kind: Deployment
metadata:
  name: execution-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: execution
  template:
    metadata:
      labels:
        app: execution
    spec:
      containers:
        - name: execution
          image: ghcr.io/uengine-oss/process-gpt-execution:d5ba912
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              protocol: TCP
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secret
                  key: OPENAI_API_KEY
            - name: SUPABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: my-config
                  key: SUPABASE_URL
            - name: SUPABASE_KEY
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: SERVICE_ROLE_KEY
            - name: SUPABASE_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: JWT_SECRET
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: DB_PASSWORD
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: DB_PORT
            - name: ENV
              value: development
            - name: LANGSMITH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: langsmith-secrets
                  key: LANGSMITH_API_KEY
            - name: LANGSMITH_PROJECT
              valueFrom:
                secretKeyRef:
                  name: langsmith-secrets
                  key: LANGSMITH_PROJECT
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              ephemeral-storage: 1Gi
          volumeMounts:
            - name: firebase-credentials
              mountPath: /etc/secrets
              readOnly: true
      volumes:
        - name: firebase-credentials
          secret:
            secretName: firebase-credentials

---
apiVersion: v1
kind: Service
metadata:
  name: execution-service
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: execution