apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-proxy-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-proxy
  template:
    metadata:
      labels:
        app: mcp-proxy
    spec:
      serviceAccount: mcp-proxy-sa
      serviceAccountName: mcp-proxy-sa
      containers:
        - name: mcp-proxy
          image: ghcr.io/uengine-oss/process-gpt-mcp-proxy:v0.3.8
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: SUPABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: my-config
                  key: SUPABASE_URL
            - name: SUPABASE_ANON_KEY
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: SUPABASE_KEY
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              ephemeral-storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mcp-proxy-svc
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: mcp-proxy