apiVersion: v1
kind: ServiceAccount
metadata:
  name: mcp-proxy-sa
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mcp-proxy-clusterrole
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - services
  - secrets
  - configmaps
  verbs:
  - get
  - list
  - create
  - delete
  - watch
  - update
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - create
  - delete
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mcp-proxy-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mcp-proxy-clusterrole
subjects:
- kind: ServiceAccount
  name: mcp-proxy-sa
  namespace: default