apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: airbnb-agent
  name: airbnb-agent
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 10002
      protocol: TCP
      targetPort: 10002
  selector:
    app: airbnb-agent
  sessionAffinity: None
  type: ClusterIP
