apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: autonomous-service
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 6789
      protocol: TCP
      targetPort: 6789
  selector:
    app: autonomous
  sessionAffinity: None
  type: ClusterIP
