apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: completion-service
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: completion
  sessionAffinity: None
  type: ClusterIP
