apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: frontend-service
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 5173
      protocol: TCP
      targetPort: 8080
  selector:
    app: frontend
  sessionAffinity: None
  type: ClusterIP
