apiVersion: v1
kind: Service
metadata:
  name: gateway
  # namespace: dev
  labels:
    app: gateway
spec:
  type: LoadBalancer
  selector:
    app: gateway
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: vnc
      protocol: TCP
      port: 6080
      targetPort: 8080
    - name: api
      protocol: TCP
      port: 5001
      targetPort: 8080
